### ISSUE TITLE
Create Events Page for users and admin

### ISSUE THREAD

**Issue by dstingaciu** [ruhacks/Frontend_2021#16]
Create an events page on the website that display when events setup in the portal are happening. Thus we need to create an events tab for users that:

- [x] Displays all events in a list or in a calendar
- [x] User is able to expand an event for more information
- [x] Links for the event?

For the admin we need an event creation page in an event tab

- [x] create event with title, description, date/time it's happening

In the back end:

- [x]  We need a collection to store all these events
- [x] Set security rules for the collection so only admins can write but users can only read

**Comment by farhan-mohammed** [comment]
Got the code ready for generating a custom calendar: https://github.com/farhan-mohammed/react-day-event-calendar and the data type. The data saved will be in the format: 

```js
[
    { id: 1, start: 0, end: 30 },
    { id: 2, start: 30, end: 100 },
    { id: 3, start: 80, end: 160 },
    ...
]
```

where start and end are the minutes of when the event starts and ends. 

Have to finalize other properties of an event which may include:
- Title (Eg: Introduction to Git) 
- Description 
- Host
- Event Type
- Platform
